require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-faker

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'Gemfile.lock'
    - 'config.ru'
    - 'Rakefile'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'script/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#']

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ArrayCoercion:
  Enabled: false

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/Documentation:
  Enabled: false