Player.create(name: "Salvatore Sirigu", position: :goalkeeper, team: Team.find_by(name: "Italy"))
Player.create(name: "Giovanni Di Lorenzo", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Giorgio Chiellini", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Leonardo Spinazzola", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Manuel Locatelli", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Marco Verratti", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Lorenzo Pellegrini", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Jorginho", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Andrea Belotti", position: :forward, team: Team.find_by(name: "Italy"))
Player.create(name: "Lorenzo Insigne", position: :forward, team: Team.find_by(name: "Italy"))
Player.create(name: "Domenico Berardi", position: :forward, team: Team.find_by(name: "Italy"))
Player.create(name: "Matteo Pessina", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Emerson", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Federico Chiesa", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Francesco Acerbi", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Bryan Cristante", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Ciro Immobile", position: :forward, team: Team.find_by(name: "Italy"))
Player.create(name: "Nicolò Barella", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Leonardo Bonucci", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Federico Bernardeschi", position: :midfielder, team: Team.find_by(name: "Italy"))
Player.create(name: "Gianluigi Donnarumma", position: :goalkeeper, team: Team.find_by(name: "Italy"))
Player.create(name: "Giacomo Raspadori", position: :forward, team: Team.find_by(name: "Italy"))
Player.create(name: "Alessandro Bastoni", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Alessandro Florenzi", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Rafael Tolói", position: :defender, team: Team.find_by(name: "Italy"))
Player.create(name: "Alex Meret", position: :goalkeeper, team: Team.find_by(name: "Italy"))
Player.create(name: "Yann Sommer", position: :goalkeeper, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Kevin Mbabu", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Silvan Widmer", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Nico Elvedi", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Manuel Akanji", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Denis Zakaria", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Breel Embolo", position: :forward, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Remo Freuler", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Haris Seferović", position: :forward, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Granit Xhaka", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Ruben Vargas", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Yvon Mvogo", position: :goalkeeper, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Ricardo Rodríguez", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Steven Zuber", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Djibril Sow", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Christian Fassnacht", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Loris Benito", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Admir Mehmedi", position: :forward, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Mario Gavranović", position: :forward, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Edimilson Fernandes", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Jonas Omlin", position: :goalkeeper, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Fabian Schär", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Xherdan Shaqiri", position: :midfielder, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Bećir Omeragić", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Eray Cömert", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Jordan Lotomba", position: :defender, team: Team.find_by(name: "Switzerland"))
Player.create(name: "Mert Günok", position: :goalkeeper, team: Team.find_by(name: "Turkey"))
Player.create(name: "Zeki Çelik", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Merih Demiral", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Çağlar Söyüncü", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Okay Yokuşlu", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Ozan Tufan", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Cengiz Ünder", position: :forward, team: Team.find_by(name: "Turkey"))
Player.create(name: "Dorukhan Toköz", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Kenan Karaman", position: :forward, team: Team.find_by(name: "Turkey"))
Player.create(name: "Hakan Çalhanoğlu", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Yusuf Yazıcı", position: :forward, team: Team.find_by(name: "Turkey"))
Player.create(name: "Altay Bayındır", position: :goalkeeper, team: Team.find_by(name: "Turkey"))
Player.create(name: "Umut Meraş", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Taylan Antalyalı", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Ozan Kabak", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Enes Ünal", position: :forward, team: Team.find_by(name: "Turkey"))
Player.create(name: "Burak Yılmaz", position: :forward, team: Team.find_by(name: "Turkey"))
Player.create(name: "Rıdvan Yılmaz", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Orkun Kökçü", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Abdülkadir Ömür", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "İrfan Kahveci", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Kaan Ayhan", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Uğurcan Çakır", position: :goalkeeper, team: Team.find_by(name: "Turkey"))
Player.create(name: "Kerem Aktürkoğlu", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Mert Müldür", position: :defender, team: Team.find_by(name: "Turkey"))
Player.create(name: "Halil Dervişoğlu", position: :midfielder, team: Team.find_by(name: "Turkey"))
Player.create(name: "Wayne Hennessey", position: :goalkeeper, team: Team.find_by(name: "Wales"))
Player.create(name: "Chris Gunter", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Neco Williams", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Ben Davies", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Tom Lockyer", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Joe Rodon", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Joe Allen", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Harry Wilson", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Tyler Roberts", position: :forward, team: Team.find_by(name: "Wales"))
Player.create(name: "Aaron Ramsey", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Gareth Bale", position: :forward, team: Team.find_by(name: "Wales"))
Player.create(name: "Danny Ward", position: :goalkeeper, team: Team.find_by(name: "Wales"))
Player.create(name: "Kieffer Moore", position: :forward, team: Team.find_by(name: "Wales"))
Player.create(name: "Connor Roberts", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Ethan Ampadu", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Joe Morrell", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Rhys Norrington-Davies", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Jonny Williams", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "David Brooks", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Daniel James", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Adam Davies", position: :goalkeeper, team: Team.find_by(name: "Wales"))
Player.create(name: "Chris Mepham", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Dylan Levitt", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Ben Cabango", position: :defender, team: Team.find_by(name: "Wales"))
Player.create(name: "Rubin Colwill", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Matthew Smith", position: :midfielder, team: Team.find_by(name: "Wales"))
Player.create(name: "Thibaut Courtois", position: :goalkeeper, team: Team.find_by(name: "Belgium"))
Player.create(name: "Toby Alderweireld", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Thomas Vermaelen", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Dedryck Boyata", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Jan Vertonghen", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Axel Witsel", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Kevin De Bruyne", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Youri Tielemans", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Romelu Lukaku", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Eden Hazard", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Yannick Carrasco", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Simon Mignolet", position: :goalkeeper, team: Team.find_by(name: "Belgium"))
Player.create(name: "Matz Sels", position: :goalkeeper, team: Team.find_by(name: "Belgium"))
Player.create(name: "Dries Mertens", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Thomas Meunier", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Thorgan Hazard", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Hans Vanaken", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Jason Denayer", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Leander Dendoncker", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Christian Benteke", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Timothy Castagne", position: :defender, team: Team.find_by(name: "Belgium"))
Player.create(name: "Nacer Chadli", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Michy Batshuayi", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Leandro Trossard", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Jérémy Doku", position: :forward, team: Team.find_by(name: "Belgium"))
Player.create(name: "Dennis Praet", position: :midfielder, team: Team.find_by(name: "Belgium"))
Player.create(name: "Kasper Schmeichel", position: :goalkeeper, team: Team.find_by(name: "Denmark"))
Player.create(name: "Joachim Andersen", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Jannik Vestergaard", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Simon Kjær", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Joakim Mæhle", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Andreas Christensen", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Robert Skov", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Thomas Delaney", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Martin Braithwaite", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Christian Eriksen", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Andreas Skov Olsen", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Kasper Dolberg", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Mathias Jørgensen", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Mikkel Damsgaard", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Christian Nørgaard", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Jonas Lössl", position: :goalkeeper, team: Team.find_by(name: "Denmark"))
Player.create(name: "Jens Stryger Larsen", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Daniel Wass", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Jonas Wind", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Yussuf Poulsen", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Andreas Cornelius", position: :forward, team: Team.find_by(name: "Denmark"))
Player.create(name: "Frederik Rønnow", position: :goalkeeper, team: Team.find_by(name: "Denmark"))
Player.create(name: "Pierre-Emile Højbjerg", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Mathias Jensen", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Anders Christiansen", position: :midfielder, team: Team.find_by(name: "Denmark"))
Player.create(name: "Nicolai Boilesen", position: :defender, team: Team.find_by(name: "Denmark"))
Player.create(name: "Lukáš Hrádecký", position: :goalkeeper, team: Team.find_by(name: "Finland"))
Player.create(name: "Paulus Arajuuri", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Daniel O'Shaughnessy", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Joona Toivio", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Leo Väisänen", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Glen Kamara", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Robert Taylor", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Robin Lod", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Fredrik Jensen", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Teemu Pukki", position: :forward, team: Team.find_by(name: "Finland"))
Player.create(name: "Rasmus Schüller", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Jesse Joronen", position: :goalkeeper, team: Team.find_by(name: "Finland"))
Player.create(name: "Pyry Soiri", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Tim Sparv", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Niko Hämäläinen", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Thomas Lam", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Nikolai Alho", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Jere Uronen", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Joni Kauko", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Joel Pohjanpalo", position: :forward, team: Team.find_by(name: "Finland"))
Player.create(name: "Lassi Lappalainen", position: :forward, team: Team.find_by(name: "Finland"))
Player.create(name: "Jukka Raitala", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Anssi Jaakkola", position: :goalkeeper, team: Team.find_by(name: "Finland"))
Player.create(name: "Onni Valakari", position: :midfielder, team: Team.find_by(name: "Finland"))
Player.create(name: "Robert Ivanov", position: :defender, team: Team.find_by(name: "Finland"))
Player.create(name: "Marcus Forss", position: :forward, team: Team.find_by(name: "Finland"))
Player.create(name: "Anton Shunin", position: :goalkeeper, team: Team.find_by(name: "Russia"))
Player.create(name: "Mário Fernandes", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Igor Diveyev", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Vyacheslav Karavayev", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Andrei Semyonov", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Denis Cheryshev", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Magomed Ozdoyev", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Dmitri Barinov", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Aleksandr Sobolev", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Anton Zabolotny", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Roman Zobnin", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Yury Dyupin", position: :goalkeeper, team: Team.find_by(name: "Russia"))
Player.create(name: "Fyodor Kudryashov", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Georgi Dzhikiya", position: :defender, team: Team.find_by(name: "Russia"))
Player.create(name: "Aleksei Miranchuk", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Matvei Safonov", position: :goalkeeper, team: Team.find_by(name: "Russia"))
Player.create(name: "Aleksandr Golovin", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Yuri Zhirkov", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Rifat Zhemaletdinov", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Aleksei Ionov", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Daniil Fomin", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Artem Dzyuba", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Daler Kuzyayev", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Andrei Mostovoy", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Denis Makarov", position: :forward, team: Team.find_by(name: "Russia"))
Player.create(name: "Maksim Mukhin", position: :midfielder, team: Team.find_by(name: "Russia"))
Player.create(name: "Alexander Schlager", position: :goalkeeper, team: Team.find_by(name: "Austria"))
Player.create(name: "Andreas Ulmer", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Aleksandar Dragović", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Martin Hinteregger", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Stefan Posch", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Stefan Ilsanker", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Marko Arnautović", position: :forward, team: Team.find_by(name: "Austria"))
Player.create(name: "David Alaba", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Marcel Sabitzer", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Florian Grillitsch", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Michael Gregoritsch", position: :forward, team: Team.find_by(name: "Austria"))
Player.create(name: "Pavao Pervan", position: :goalkeeper, team: Team.find_by(name: "Austria"))
Player.create(name: "Daniel Bachmann", position: :goalkeeper, team: Team.find_by(name: "Austria"))
Player.create(name: "Julian Baumgartlinger", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Philipp Lienhart", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Christopher Trimmel", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Louis Schaub", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Alessandro Schöpf", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Christoph Baumgartner", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Karim Onisiwo", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Stefan Lainer", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Valentino Lazaro", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Xaver Schlager", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Konrad Laimer", position: :midfielder, team: Team.find_by(name: "Austria"))
Player.create(name: "Saša Kalajdžić", position: :forward, team: Team.find_by(name: "Austria"))
Player.create(name: "Marco Friedl", position: :defender, team: Team.find_by(name: "Austria"))
Player.create(name: "Maarten Stekelenburg", position: :goalkeeper, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Joël Veltman", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Matthijs de Ligt", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Nathan Aké", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Owen Wijndal", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Stefan de Vrij", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Steven Berghuis", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Georginio Wijnaldum", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Luuk de Jong", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Memphis Depay", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Quincy Promes", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Patrick van Aanholt", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Tim Krul", position: :goalkeeper, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Davy Klaassen", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Marten de Roon", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Ryan Gravenberch", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Daley Blind", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Donyell Malen", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Wout Weghorst", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Frenkie de Jong", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Denzel Dumfries", position: :defender, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Marco Bizot", position: :goalkeeper, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Teun Koopmeiners", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Jurriën Timber", position: :midfielder, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Cody Gakpo", position: :forward, team: Team.find_by(name: "Netherlands"))
Player.create(name: "Stole Dimitrievski", position: :goalkeeper, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Egzon Bejtulai", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Gjoko Zajkov", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Kire Ristevski", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Arijan Ademi", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Visar Musliu", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Ivan Trichkovski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Ezgjan Alioski", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Aleksandar Trajkovski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Goran Pandev", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Ferhan Hasani", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Risto Jankov", position: :goalkeeper, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Stefan Ristovski", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Darko Velkovski", position: :defender, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Tihomir Kostadinov", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Boban Nikolov", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Enis Bardhi", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Vlatko Stojanovski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Krste Velkoski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Stefan Spirovski", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Elif Elmas", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Damjan Shishkovski", position: :goalkeeper, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Marjan Radeski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Daniel Avramovski", position: :forward, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Darko Churlinov", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Milan Ristovski", position: :midfielder, team: Team.find_by(name: "North Macedonia"))
Player.create(name: "Heorhiy Bushchan", position: :goalkeeper, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Eduard Sobol", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Heorhiy Sudakov", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Serhiy Kryvtsov", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Serhiy Sydorchuk", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Taras Stepanenko", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Andriy Yarmolenko", position: :forward, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Ruslan Malinovskyi", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Roman Yaremchuk", position: :forward, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Mykola Shaparenko", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Marlos", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Andriy Pyatov", position: :goalkeeper, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Illya Zabarnyi", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Yevhenii Makarenko", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Viktor Tsyhankov", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Vitaliy Mykolenko", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Oleksandr Zinchenko", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Roman Bezus", position: :midfielder, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Artem Besyedin", position: :forward, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Oleksandr Zubkov", position: :forward, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Oleksandr Karavayev", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Mykola Matviyenko", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Anatoliy Trubin", position: :goalkeeper, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Oleksandr Tymchyk", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Denys Popov", position: :defender, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Artem Dovbyk", position: :forward, team: Team.find_by(name: "Ukraine"))
Player.create(name: "Dominik Livaković", position: :goalkeeper, team: Team.find_by(name: "Croatia"))
Player.create(name: "Šime Vrsaljko", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Borna Barišić", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Ivan Perišić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Duje Ćaleta-Car", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Dejan Lovren", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Josip Brekalo", position: :forward, team: Team.find_by(name: "Croatia"))
Player.create(name: "Mateo Kovačić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Andrej Kramarić", position: :forward, team: Team.find_by(name: "Croatia"))
Player.create(name: "Luka Modrić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Marcelo Brozović", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Lovre Kalinić", position: :goalkeeper, team: Team.find_by(name: "Croatia"))
Player.create(name: "Nikola Vlašić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Ante Budimir", position: :forward, team: Team.find_by(name: "Croatia"))
Player.create(name: "Mario Pašalić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Mile Škorić", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Ante Rebić", position: :forward, team: Team.find_by(name: "Croatia"))
Player.create(name: "Mislav Oršić", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Milan Badelj", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Bruno Petković", position: :forward, team: Team.find_by(name: "Croatia"))
Player.create(name: "Domagoj Vida", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Josip Juranović", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Simon Sluga", position: :goalkeeper, team: Team.find_by(name: "Croatia"))
Player.create(name: "Domagoj Bradarić", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Joško Gvardiol", position: :defender, team: Team.find_by(name: "Croatia"))
Player.create(name: "Luka Ivanušec", position: :midfielder, team: Team.find_by(name: "Croatia"))
Player.create(name: "Tomáš Vaclík", position: :goalkeeper, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Pavel Kadeřábek", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Ondřej Čelůstka", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jakub Brabec", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Vladimír Coufal", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Tomáš Kalas", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Antonín Barák", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Vladimír Darida", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Tomáš Holeš", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Patrik Schick", position: :forward, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Michael Krmenčík", position: :forward, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Lukáš Masopust", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Petr Ševčík", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jakub Jankto", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Tomáš Souček", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Aleš Mandous", position: :goalkeeper, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "David Zima", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jan Bořil", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Adam Hložek", position: :forward, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Matěj Vydra", position: :forward, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Alex Král", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Aleš Matějů", position: :defender, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jiří Pavlenka", position: :goalkeeper, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Tomáš Pekhart", position: :forward, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jakub Pešek", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Michal Sadílek", position: :midfielder, team: Team.find_by(name: "Czech Republic"))
Player.create(name: "Jordan Pickford", position: :goalkeeper, team: Team.find_by(name: "England"))
Player.create(name: "Kyle Walker", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Luke Shaw", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Declan Rice", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "John Stones", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Harry Maguire", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Jack Grealish", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Jordan Henderson", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Harry Kane", position: :forward, team: Team.find_by(name: "England"))
Player.create(name: "Raheem Sterling", position: :forward, team: Team.find_by(name: "England"))
Player.create(name: "Marcus Rashford", position: :forward, team: Team.find_by(name: "England"))
Player.create(name: "Kieran Trippier", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Dean Henderson", position: :goalkeeper, team: Team.find_by(name: "England"))
Player.create(name: "Kalvin Phillips", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Tyrone Mings", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Conor Coady", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Jadon Sancho", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Dominic Calvert-Lewin", position: :forward, team: Team.find_by(name: "England"))
Player.create(name: "Mason Mount", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Phil Foden", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Ben Chilwell", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Ben White", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Sam Johnstone", position: :goalkeeper, team: Team.find_by(name: "England"))
Player.create(name: "Reece James", position: :defender, team: Team.find_by(name: "England"))
Player.create(name: "Bukayo Saka", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "Jude Bellingham", position: :midfielder, team: Team.find_by(name: "England"))
Player.create(name: "David Marshall", position: :goalkeeper, team: Team.find_by(name: "Scotland"))
Player.create(name: "Stephen O'Donnell", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Andrew Robertson", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Scott McTominay", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Grant Hanley", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Kieran Tierney", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "John McGinn", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Callum McGregor", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Lyndon Dykes", position: :forward, team: Team.find_by(name: "Scotland"))
Player.create(name: "Ché Adams", position: :forward, team: Team.find_by(name: "Scotland"))
Player.create(name: "Ryan Christie", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Craig Gordon", position: :goalkeeper, team: Team.find_by(name: "Scotland"))
Player.create(name: "Greg Taylor", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "John Fleck", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Declan Gallagher", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Liam Cooper", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Stuart Armstrong", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "David Turnbull", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Kevin Nisbet", position: :forward, team: Team.find_by(name: "Scotland"))
Player.create(name: "Ryan Fraser", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Jon McLaughlin", position: :goalkeeper, team: Team.find_by(name: "Scotland"))
Player.create(name: "Nathan Patterson", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Billy Gilmour", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Jack Hendry", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "James Forrest", position: :midfielder, team: Team.find_by(name: "Scotland"))
Player.create(name: "Scott McKenna", position: :defender, team: Team.find_by(name: "Scotland"))
Player.create(name: "Wojciech Szczęsny", position: :goalkeeper, team: Team.find_by(name: "Poland"))
Player.create(name: "Kamil Piątkowski", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Paweł Dawidowicz", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Tomasz Kędziora", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Jan Bednarek", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Kacper Kozłowski", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Karol Linetty", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Robert Lewandowski", position: :forward, team: Team.find_by(name: "Poland"))
Player.create(name: "Grzegorz Krychowiak", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Karol Świderski", position: :forward, team: Team.find_by(name: "Poland"))
Player.create(name: "Łukasz Skorupski", position: :goalkeeper, team: Team.find_by(name: "Poland"))
Player.create(name: "Maciej Rybus", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Mateusz Klich", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Kamil Glik", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Jakub Moder", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Przemysław Płacheta", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Bartosz Bereszyński", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Przemysław Frankowski", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Piotr Zieliński", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Kamil Jóźwiak", position: :midfielder, team: Team.find_by(name: "Poland"))
Player.create(name: "Łukasz Fabiański", position: :goalkeeper, team: Team.find_by(name: "Poland"))
Player.create(name: "Dawid Kownacki", position: :forward, team: Team.find_by(name: "Poland"))
Player.create(name: "Jakub Świerczok", position: :forward, team: Team.find_by(name: "Poland"))
Player.create(name: "Michał Helik", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Tymoteusz Puchacz", position: :defender, team: Team.find_by(name: "Poland"))
Player.create(name: "Martin Dúbravka", position: :goalkeeper, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Peter Pekarík", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Denis Vavro", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Martin Valjent", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Ľubomír Šatka", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Ján Greguš", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Vladimír Weiss", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Ondrej Duda", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Róbert Boženík", position: :forward, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Tomáš Suslov", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "László Bénes", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Dušan Kuciak", position: :goalkeeper, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Patrik Hrošovský", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Milan Škriniar", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Tomáš Hubočan", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Dávid Hancko", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Marek Hamšík", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Lukáš Haraslín", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Juraj Kucka", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Róbert Mak", position: :forward, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Michal Ďuriš", position: :forward, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Stanislav Lobotka", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Marek Rodák", position: :goalkeeper, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Martin Koscelník", position: :defender, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Jakub Hromada", position: :midfielder, team: Team.find_by(name: "Slovakia"))
Player.create(name: "Ivan Schranz", position: :forward, team: Team.find_by(name: "Slovakia"))
Player.create(name: "David de Gea", position: :goalkeeper, team: Team.find_by(name: "Spain"))
Player.create(name: "César Azpilicueta", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Diego Llorente", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Pau Torres", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Sergio Busquets", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Marcos Llorente", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Álvaro Morata", position: :forward, team: Team.find_by(name: "Spain"))
Player.create(name: "Koke", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Gerard Moreno", position: :forward, team: Team.find_by(name: "Spain"))
Player.create(name: "Thiago", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Ferran Torres", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Eric García", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Robert Sánchez", position: :goalkeeper, team: Team.find_by(name: "Spain"))
Player.create(name: "José Gayà", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Rodri", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Fabián Ruiz", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Jordi Alba", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Dani Olmo", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Adama Traoré", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Mikel Oyarzabal", position: :forward, team: Team.find_by(name: "Spain"))
Player.create(name: "Pablo Sarabia", position: :midfielder, team: Team.find_by(name: "Spain"))
Player.create(name: "Unai Simón", position: :goalkeeper, team: Team.find_by(name: "Spain"))
Player.create(name: "Aymeric Laporte", position: :defender, team: Team.find_by(name: "Spain"))
Player.create(name: "Pedri", position: :forward, team: Team.find_by(name: "Spain"))
Player.create(name: "Robin Olsen", position: :goalkeeper, team: Team.find_by(name: "Sweden"))
Player.create(name: "Mikael Lustig", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Victor Lindelöf", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Andreas Granqvist", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Pierre Bengtsson", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Ludwig Augustinsson", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Sebastian Larsson", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Albin Ekdal", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Marcus Berg", position: :forward, team: Team.find_by(name: "Sweden"))
Player.create(name: "Emil Forsberg", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Alexander Isak", position: :forward, team: Team.find_by(name: "Sweden"))
Player.create(name: "Karl-Johan Johnsson", position: :goalkeeper, team: Team.find_by(name: "Sweden"))
Player.create(name: "Gustav Svensson", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Filip Helander", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Ken Sema", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Emil Krafth", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Viktor Claesson", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Pontus Jansson", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Mattias Svanberg", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Kristoffer Olsson", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Dejan Kulusevski", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Robin Quaison", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Kristoffer Nordfeldt", position: :goalkeeper, team: Team.find_by(name: "Sweden"))
Player.create(name: "Marcus Danielson", position: :defender, team: Team.find_by(name: "Sweden"))
Player.create(name: "Jordan Larsson", position: :forward, team: Team.find_by(name: "Sweden"))
Player.create(name: "Jens Cajuste", position: :midfielder, team: Team.find_by(name: "Sweden"))
Player.create(name: "Hugo Lloris", position: :goalkeeper, team: Team.find_by(name: "France"))
Player.create(name: "Benjamin Pavard", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Presnel Kimpembe", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Raphaël Varane", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Clément Lenglet", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Paul Pogba", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Antoine Griezmann", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Thomas Lemar", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Olivier Giroud", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Kylian Mbappé", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Ousmane Dembélé", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Corentin Tolisso", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "N'Golo Kanté", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Adrien Rabiot", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Kurt Zouma", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Steve Mandanda", position: :goalkeeper, team: Team.find_by(name: "France"))
Player.create(name: "Moussa Sissoko", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Lucas Digne", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Karim Benzema", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Kingsley Coman", position: :midfielder, team: Team.find_by(name: "France"))
Player.create(name: "Lucas Hernandez", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Wissam Ben Yedder", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Mike Maignan", position: :goalkeeper, team: Team.find_by(name: "France"))
Player.create(name: "Léo Dubois", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Jules Koundé", position: :defender, team: Team.find_by(name: "France"))
Player.create(name: "Marcus Thuram", position: :forward, team: Team.find_by(name: "France"))
Player.create(name: "Manuel Neuer", position: :goalkeeper, team: Team.find_by(name: "Germany"))
Player.create(name: "Antonio Rüdiger", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Marcel Halstenberg", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Matthias Ginter", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Mats Hummels", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Joshua Kimmich", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Kai Havertz", position: :forward, team: Team.find_by(name: "Germany"))
Player.create(name: "Toni Kroos", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Kevin Volland", position: :forward, team: Team.find_by(name: "Germany"))
Player.create(name: "Serge Gnabry", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Timo Werner", position: :forward, team: Team.find_by(name: "Germany"))
Player.create(name: "Bernd Leno", position: :goalkeeper, team: Team.find_by(name: "Germany"))
Player.create(name: "Jonas Hofmann", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Jamal Musiala", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Niklas Süle", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Lukas Klostermann", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Florian Neuhaus", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Leon Goretzka", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Leroy Sané", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Robin Gosens", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "İlkay Gündoğan", position: :midfielder, team: Team.find_by(name: "Germany"))
Player.create(name: "Kevin Trapp", position: :goalkeeper, team: Team.find_by(name: "Germany"))
Player.create(name: "Emre Can", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Robin Koch", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Thomas Müller", position: :forward, team: Team.find_by(name: "Germany"))
Player.create(name: "Christian Günter", position: :defender, team: Team.find_by(name: "Germany"))
Player.create(name: "Péter Gulácsi", position: :goalkeeper, team: Team.find_by(name: "Hungry"))
Player.create(name: "Ádám Lang", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Ákos Kecskés", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Attila Szalai", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Attila Fiola", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Willi Orbán", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Loïc Négo", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Ádám Nagy", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Ádám Szalai", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "Tamás Cseri", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Filip Holender", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "Dénes Dibusz", position: :goalkeeper, team: Team.find_by(name: "Hungry"))
Player.create(name: "András Schäfer", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Gergő Lovrencsics", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "László Kleinheisler", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Dániel Gazdag", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Roland Varga", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Dávid Sigér", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Kevin Varga", position: :midfielder, team: Team.find_by(name: "Hungry"))
Player.create(name: "Roland Sallai", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "Endre Botka", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Ádám Bogdán", position: :goalkeeper, team: Team.find_by(name: "Hungry"))
Player.create(name: "Nemanja Nikolić", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "Szabolcs Schön", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "János Hahn", position: :forward, team: Team.find_by(name: "Hungry"))
Player.create(name: "Bendegúz Bolla", position: :defender, team: Team.find_by(name: "Hungry"))
Player.create(name: "Rui Patrício", position: :goalkeeper, team: Team.find_by(name: "Portugal"))
Player.create(name: "Nélson Semedo", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "Pepe", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "Rúben Dias", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "Raphaël Guerreiro", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "José Fonte", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "Cristiano Ronaldo", position: :forward, team: Team.find_by(name: "Portugal"))
Player.create(name: "João Moutinho", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "André Silva", position: :forward, team: Team.find_by(name: "Portugal"))
Player.create(name: "Bernardo Silva", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Bruno Fernandes", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Anthony Lopes", position: :goalkeeper, team: Team.find_by(name: "Portugal"))
Player.create(name: "Danilo Pereira", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "William Carvalho", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Rafa Silva", position: :forward, team: Team.find_by(name: "Portugal"))
Player.create(name: "Renato Sanches", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Gonçalo Guedes", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Rúben Neves", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Pedro Gonçalves", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "João Cancelo", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "Diogo Jota", position: :forward, team: Team.find_by(name: "Portugal"))
Player.create(name: "Rui Silva", position: :goalkeeper, team: Team.find_by(name: "Portugal"))
Player.create(name: "João Félix", position: :forward, team: Team.find_by(name: "Portugal"))
Player.create(name: "Sérgio Oliveira", position: :midfielder, team: Team.find_by(name: "Portugal"))
Player.create(name: "Nuno Mendes", position: :defender, team: Team.find_by(name: "Portugal"))
Player.create(name: "João Palhinha", position: :midfielder, team: Team.find_by(name: "Portugal"))
